# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='grpc',
  syntax='proto3',
  serialized_pb=_b('\n\x10helloworld.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"%\n\x04Note\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"D\n\x0fregisterdetails\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"<\n\x0b\x41PIResponse\x12\x17\n\x0fresponsemessage\x18\x01 \x01(\t\x12\x14\n\x0cresponsecode\x18\x02 \x01(\x05\"B\n\x0f\x43hatUserMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t2\xec\x02\n\nChatServer\x12\'\n\nChatStream\x12\x0b.grpc.Empty\x1a\n.grpc.Note0\x01\x12#\n\x08SendNote\x12\n.grpc.Note\x1a\x0b.grpc.Empty\x12(\n\rSendNotemulti\x12\n.grpc.Note\x1a\x0b.grpc.Empty\x12.\n\x08register\x12\x15.grpc.registerdetails\x1a\x0b.grpc.Empty\x12.\n\x05login\x12\x12.grpc.LoginRequest\x1a\x11.grpc.APIResponse\x12(\n\x06logout\x12\x0b.grpc.Empty\x1a\x11.grpc.APIResponse\x12/\n\x08\x43hatUser\x12\x15.grpc.ChatUserMessage\x1a\n.grpc.Note0\x01\x12+\n\x0e\x43hatStreamUser\x12\x0b.grpc.Empty\x1a\n.grpc.Note0\x01\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='grpc.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=33,
)


_NOTE = _descriptor.Descriptor(
  name='Note',
  full_name='grpc.Note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grpc.Note.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc.Note.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=72,
)


_REGISTERDETAILS = _descriptor.Descriptor(
  name='registerdetails',
  full_name='grpc.registerdetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='grpc.registerdetails.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='grpc.registerdetails.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='grpc.registerdetails.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=142,
)


_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='grpc.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='grpc.LoginRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='grpc.LoginRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=194,
)


_APIRESPONSE = _descriptor.Descriptor(
  name='APIResponse',
  full_name='grpc.APIResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responsemessage', full_name='grpc.APIResponse.responsemessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responsecode', full_name='grpc.APIResponse.responsecode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=256,
)


_CHATUSERMESSAGE = _descriptor.Descriptor(
  name='ChatUserMessage',
  full_name='grpc.ChatUserMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grpc.ChatUserMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc.ChatUserMessage.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='grpc.ChatUserMessage.receiver', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=324,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Note'] = _NOTE
DESCRIPTOR.message_types_by_name['registerdetails'] = _REGISTERDETAILS
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['APIResponse'] = _APIRESPONSE
DESCRIPTOR.message_types_by_name['ChatUserMessage'] = _CHATUSERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), dict(
  DESCRIPTOR = _NOTE,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Note)
  ))
_sym_db.RegisterMessage(Note)

registerdetails = _reflection.GeneratedProtocolMessageType('registerdetails', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERDETAILS,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:grpc.registerdetails)
  ))
_sym_db.RegisterMessage(registerdetails)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUEST,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:grpc.LoginRequest)
  ))
_sym_db.RegisterMessage(LoginRequest)

APIResponse = _reflection.GeneratedProtocolMessageType('APIResponse', (_message.Message,), dict(
  DESCRIPTOR = _APIRESPONSE,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:grpc.APIResponse)
  ))
_sym_db.RegisterMessage(APIResponse)

ChatUserMessage = _reflection.GeneratedProtocolMessageType('ChatUserMessage', (_message.Message,), dict(
  DESCRIPTOR = _CHATUSERMESSAGE,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:grpc.ChatUserMessage)
  ))
_sym_db.RegisterMessage(ChatUserMessage)



_CHATSERVER = _descriptor.ServiceDescriptor(
  name='ChatServer',
  full_name='grpc.ChatServer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=327,
  serialized_end=691,
  methods=[
  _descriptor.MethodDescriptor(
    name='ChatStream',
    full_name='grpc.ChatServer.ChatStream',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_NOTE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendNote',
    full_name='grpc.ChatServer.SendNote',
    index=1,
    containing_service=None,
    input_type=_NOTE,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendNotemulti',
    full_name='grpc.ChatServer.SendNotemulti',
    index=2,
    containing_service=None,
    input_type=_NOTE,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='register',
    full_name='grpc.ChatServer.register',
    index=3,
    containing_service=None,
    input_type=_REGISTERDETAILS,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='login',
    full_name='grpc.ChatServer.login',
    index=4,
    containing_service=None,
    input_type=_LOGINREQUEST,
    output_type=_APIRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='logout',
    full_name='grpc.ChatServer.logout',
    index=5,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_APIRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ChatUser',
    full_name='grpc.ChatServer.ChatUser',
    index=6,
    containing_service=None,
    input_type=_CHATUSERMESSAGE,
    output_type=_NOTE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ChatStreamUser',
    full_name='grpc.ChatServer.ChatStreamUser',
    index=7,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_NOTE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVER)

DESCRIPTOR.services_by_name['ChatServer'] = _CHATSERVER

# @@protoc_insertion_point(module_scope)
